import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";

const Family = localFont({
  src: "./fonts/Family/IRAN(FaNum).woff"
})

export const metadata: Metadata = {
  title: "دندان پزشکی دکتر سعید دریس",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={Family.className}
      >
        <NavBar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
